spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
