spring:
  application:
    name: AgoraCampus

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/agora_campus}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
