spring:
  application:
    name: AgoraCampus

  datasource:
    url: jdbc:postgresql://localhost:5432/agora_campus
    username: postgres
    password: aricelul
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
