-- AgoraCampus baseline schema (all JPA entities).
-- Matches entity mappings as of Flyway introduction.

CREATE TABLE app_users (
    app_user_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_id   VARCHAR(100)  NOT NULL,
    email         VARCHAR(255)  NOT NULL,
    username      VARCHAR(100)  NOT NULL,
    created_at    TIMESTAMPTZ   NOT NULL,
    CONSTRAINT uk_app_users_keycloak_id UNIQUE (keycloak_id),
    CONSTRAINT uk_app_users_email UNIQUE (email),
    CONSTRAINT uk_app_users_username UNIQUE (username)
);

CREATE TABLE profiles (
    profile_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id      BIGINT       NOT NULL,
    profile_type     VARCHAR(32)  NOT NULL,
    headline         VARCHAR(255),
    description      TEXT,
    location         VARCHAR(255),
    website          VARCHAR(512),
    profile_picture  VARCHAR(512),
    cover_image      VARCHAR(512),
    updated_at       TIMESTAMPTZ  NOT NULL,
    CONSTRAINT uk_profiles_app_user_id UNIQUE (app_user_id),
    CONSTRAINT fk_profiles_app_user FOREIGN KEY (app_user_id) REFERENCES app_users (app_user_id)
);

CREATE TABLE individual_profiles (
    individual_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id            BIGINT       NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    phone                 VARCHAR(50),
    cv_document           VARCHAR(512),
    CONSTRAINT uk_individual_profiles_profile_id UNIQUE (profile_id),
    CONSTRAINT fk_individual_profiles_profile FOREIGN KEY (profile_id) REFERENCES profiles (profile_id)
);

CREATE TABLE organization_profiles (
    organization_profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id              BIGINT       NOT NULL,
    organization_name       VARCHAR(255) NOT NULL,
    phone                   VARCHAR(50),
    industry                VARCHAR(255),
    specialties             VARCHAR(255),
    CONSTRAINT uk_organization_profiles_profile_id UNIQUE (profile_id),
    CONSTRAINT fk_organization_profiles_profile FOREIGN KEY (profile_id) REFERENCES profiles (profile_id)
);

CREATE TABLE background (
    background_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    individual_profile_id BIGINT       NOT NULL,
    type                  VARCHAR(32)  NOT NULL,
    title                 VARCHAR(255) NOT NULL,
    description           TEXT,
    start_date            DATE         NOT NULL,
    end_date              DATE,
    currently_ongoing     BOOLEAN,
    CONSTRAINT fk_background_individual_profile FOREIGN KEY (individual_profile_id)
        REFERENCES individual_profiles (individual_profile_id)
);

CREATE TABLE opportunities (
    opportunity_id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    posted_by_user_id        BIGINT       NOT NULL,
    organization_profile_id  BIGINT,
    individual_profile_id    BIGINT,
    type                     VARCHAR(32)  NOT NULL,
    title                    VARCHAR(255) NOT NULL,
    location                 VARCHAR(255) NOT NULL,
    period                   VARCHAR(100) NOT NULL,
    description              TEXT         NOT NULL,
    additional_info          VARCHAR(1000),
    created_at               TIMESTAMPTZ  NOT NULL,
    CONSTRAINT fk_opportunities_posted_by_user FOREIGN KEY (posted_by_user_id)
        REFERENCES app_users (app_user_id),
    CONSTRAINT fk_opportunities_organization_profile FOREIGN KEY (organization_profile_id)
        REFERENCES organization_profiles (organization_profile_id),
    CONSTRAINT fk_opportunities_individual_profile FOREIGN KEY (individual_profile_id)
        REFERENCES individual_profiles (individual_profile_id)
);

CREATE TABLE volunteering (
    volunteering_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id  BIGINT       NOT NULL,
    cause           VARCHAR(255) NOT NULL,
    schedule        VARCHAR(255),
    benefits        VARCHAR(255),
    CONSTRAINT uk_volunteering_opportunity_id UNIQUE (opportunity_id),
    CONSTRAINT fk_volunteering_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
);

CREATE TABLE competitions (
    competition_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id BIGINT NOT NULL,
    theme          VARCHAR(200),
    eligibility    VARCHAR(300),
    prize          VARCHAR(200),
    deadline       DATE,
    CONSTRAINT uk_competitions_opportunity_id UNIQUE (opportunity_id),
    CONSTRAINT fk_competitions_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
);

CREATE TABLE internships (
    internship_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id BIGINT NOT NULL,
    duration       VARCHAR(100),
    compensation   VARCHAR(200),
    requirements   VARCHAR(500),
    CONSTRAINT uk_internships_opportunity_id UNIQUE (opportunity_id),
    CONSTRAINT fk_internships_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
);

CREATE TABLE student_projects (
    project_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id  BIGINT       NOT NULL,
    project_domain  VARCHAR(255) NOT NULL,
    required_skills TEXT,
    team_size       INTEGER,
    CONSTRAINT uk_student_projects_opportunity_id UNIQUE (opportunity_id),
    CONSTRAINT fk_student_projects_opportunity FOREIGN KEY (opportunity_id) REFERENCES opportunities (opportunity_id)
);

CREATE TABLE opportunity_applications (
    application_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opportunity_id    BIGINT      NOT NULL,
    applicant_user_id BIGINT      NOT NULL,
    status            VARCHAR(32) NOT NULL,
    applied_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_opportunity_applicant UNIQUE (opportunity_id, applicant_user_id),
    CONSTRAINT fk_opportunity_applications_opportunity FOREIGN KEY (opportunity_id)
        REFERENCES opportunities (opportunity_id),
    CONSTRAINT fk_opportunity_applications_applicant FOREIGN KEY (applicant_user_id)
        REFERENCES app_users (app_user_id)
);

CREATE TABLE connections (
    connection_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_user_id BIGINT      NOT NULL,
    receiver_user_id  BIGINT      NOT NULL,
    status            VARCHAR(32) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_connection_pair UNIQUE (requester_user_id, receiver_user_id),
    CONSTRAINT fk_connections_requester FOREIGN KEY (requester_user_id) REFERENCES app_users (app_user_id),
    CONSTRAINT fk_connections_receiver FOREIGN KEY (receiver_user_id) REFERENCES app_users (app_user_id)
);

CREATE TABLE posts (
    post_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_user_id BIGINT      NOT NULL,
    content     TEXT        NOT NULL,
    media_url   VARCHAR(1024),
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_posts_app_user FOREIGN KEY (app_user_id) REFERENCES app_users (app_user_id)
);

CREATE TABLE comments (
    comment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT      NOT NULL,
    app_user_id BIGINT      NOT NULL,
    content     TEXT        NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES posts (post_id) ON DELETE CASCADE,
    CONSTRAINT fk_comments_app_user FOREIGN KEY (app_user_id) REFERENCES app_users (app_user_id)
);

CREATE TABLE reactions (
    reaction_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       BIGINT      NOT NULL,
    app_user_id   BIGINT      NOT NULL,
    reaction_type VARCHAR(32) NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL,
    CONSTRAINT uk_reaction_post_user UNIQUE (post_id, app_user_id),
    CONSTRAINT fk_reactions_post FOREIGN KEY (post_id) REFERENCES posts (post_id) ON DELETE CASCADE,
    CONSTRAINT fk_reactions_app_user FOREIGN KEY (app_user_id) REFERENCES app_users (app_user_id)
);

CREATE TABLE messages (
    message_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_user_id   BIGINT      NOT NULL,
    receiver_user_id BIGINT      NOT NULL,
    content          TEXT        NOT NULL,
    is_read          BOOLEAN     NOT NULL,
    sent_at          TIMESTAMPTZ NOT NULL,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_user_id) REFERENCES app_users (app_user_id),
    CONSTRAINT fk_messages_receiver FOREIGN KEY (receiver_user_id) REFERENCES app_users (app_user_id)
);

CREATE INDEX idx_opportunities_type ON opportunities (type);
CREATE INDEX idx_opportunities_posted_by_user ON opportunities (posted_by_user_id);
CREATE INDEX idx_posts_app_user ON posts (app_user_id);
CREATE INDEX idx_messages_receiver ON messages (receiver_user_id);
